# arguments for dataset
dataset: cityscapes
data_root: /home/yjj/datasets/Cityscapes
nclass: 19
crop_size: 798

# arguments for training
epochs: 180
batch_size: 2 # per GPU x 4 GPUs
lr: 0.000005
lr_multi: 40.0
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 200000
conf_thresh: 0.95
distill_loss_weight: 0.03
consisteny_weight: 0.005

# arguments for model
model: dpt
backbone: dinov2_small
lock_backbone: False
