# arguments for dataset
dataset: pascal
data_root: /home/yjj/datasets/VOC2012
nclass: 21
crop_size: 518

# arguments for training
epochs: 60
batch_size: 4 # per GPU x 4 GPUs
lr: 0.000005
lr_multi: 40.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95
distill_loss_weight: 0.03
consisteny_weight: 0.005
# arguments for model
model: dpt
backbone: dinov2_small
lock_backbone: False